// Solution step fns. Return true on sucess, false if the action
// can't be done yet.

function buildTowerAt(type, [x, y]) {
    return terrain => terrain.placeTower([x, y], type);
}
function waitForWaveIndex(index) {
    return terrain => {
        const currentWave = terrain.totalWaves - terrain.upcomingWaves.length - 1;
        return currentWave >= index;
    }
}


function solveLevel(level, solution) {
    console.time('solveLevel');
    const remainingSolution = [...solution];

    let done = false;
    let output = null;
    GameState.terrain = getTerrainForLevel(level, out => {
        done = true;
        output = out;
    });

    while(!done) {
        while(remainingSolution.length) {
            const next = remainingSolution[0];
            if(next(GameState.terrain)) {
                remainingSolution.shift();
            }else{
                break;
            }
        }
        GameState.terrain.step(1/30);
    }

    console.timeEnd('solveLevel');

    return [
        GameState.terrain.health,
        GameState.terrain.mana,
    ];
}


const solutions = [
    { level: 1, solution: [
        buildTowerAt(2, [8, 9]),
        buildTowerAt(1, [10, 11]),
        waitForWaveIndex(0),
        buildTowerAt(2, [5, 12]),
        waitForWaveIndex(1),
        waitForWaveIndex(2),
        waitForWaveIndex(3),
    ] },
    { level: 2, solution: [
        buildTowerAt(2, [6, 9]),
        buildTowerAt(1, [7, 9]),
        buildTowerAt(2, [5, 13]),
        waitForWaveIndex(0),
        buildTowerAt(2, [6, 9]),
        waitForWaveIndex(1),
        waitForWaveIndex(2),
        waitForWaveIndex(3),
        buildTowerAt(1, [7, 9]),
        waitForWaveIndex(4),
    ] },
    { level: 3, solution: [
        buildTowerAt(1, [6, 3]),
        buildTowerAt(3, [9, 2]),
        buildTowerAt(2, [9, 3]),
        buildTowerAt(3, [9, 2]),
        waitForWaveIndex(0),
        buildTowerAt(3, [9, 2]),
        buildTowerAt(2, [7, 8]),
        waitForWaveIndex(1),
        buildTowerAt(1, [4, 6]),
        waitForWaveIndex(2),
        buildTowerAt(3, [4, 7]),
        buildTowerAt(3, [4, 7]),
        waitForWaveIndex(3),
        buildTowerAt(3, [4, 7]),
        buildTowerAt(2, [9, 3]),
        waitForWaveIndex(4),
        buildTowerAt(2, [9, 3]),
        waitForWaveIndex(5),
        buildTowerAt(1, [4, 6]),
        buildTowerAt(1, [4, 6]),
        buildTowerAt(3, [8, 9]),
    ] },
    // { level: 4, solution: [  // ring tower solution, less consistent than lightning
    //     buildTowerAt(1, [9, 10]),
    //     buildTowerAt(1, [9, 11]),
    //     buildTowerAt(3, [10, 10]),
    //     waitForWaveIndex(0),
    //     buildTowerAt(3, [7, 12]),
    //     buildTowerAt(3, [12, 12]),
    //     waitForWaveIndex(1),
    //     buildTowerAt(1, [12, 13]),
    //     waitForWaveIndex(2),
    //     buildTowerAt(2, [7, 11]),
    //     waitForWaveIndex(3),
    //     buildTowerAt(3, [12, 12]),
    //     buildTowerAt(2, [8, 11]),
    //     waitForWaveIndex(4),
    //     buildTowerAt(2, [8, 10]),
    //     waitForWaveIndex(5),
    //     buildTowerAt(3, [12, 12]),
    //     buildTowerAt(3, [10, 10]),
    //     buildTowerAt(3, [10, 10]),
    //     waitForWaveIndex(6),
    //     buildTowerAt(3, [7, 12]),
    //     buildTowerAt(3, [7, 12]),
    // ] },
    { level: 4, solution: [
        buildTowerAt(1, [6, 12]),
        buildTowerAt(2, [6, 11]),
        buildTowerAt(3, [12, 12]),
        waitForWaveIndex(0),
        buildTowerAt(1, [12, 13]),
        waitForWaveIndex(1),
        buildTowerAt(2, [7, 9]),
        waitForWaveIndex(2),
        buildTowerAt(1, [7, 8]),
        waitForWaveIndex(3),
        buildTowerAt(2, [7, 9]),
        waitForWaveIndex(4),
        buildTowerAt(2, [7, 9]),
        buildTowerAt(2, [6, 11]),
        waitForWaveIndex(5),
        buildTowerAt(2, [6, 11]),
        waitForWaveIndex(6),
        buildTowerAt(3, [12, 12]),
        buildTowerAt(3, [12, 12]),
    ] },
    { level: 5, solution: [
        buildTowerAt(2, [11, 14]),
        buildTowerAt(2, [6, 5]),
        buildTowerAt(2, [6, 7]),
        waitForWaveIndex(0),
        buildTowerAt(1, [6, 6]),
        buildTowerAt(3, [5, 6]),
        waitForWaveIndex(1),
        buildTowerAt(3, [5, 6]),
        buildTowerAt(3, [5, 6]),
        waitForWaveIndex(2),
        buildTowerAt(2, [2, 12]),
        waitForWaveIndex(3),
        buildTowerAt(2, [2, 12]),
        waitForWaveIndex(4),
        buildTowerAt(2, [2, 12]),
        waitForWaveIndex(5),
        buildTowerAt(3, [10, 14]),
        buildTowerAt(3, [10, 14]),
        waitForWaveIndex(6),
        buildTowerAt(2, [6, 5]),
        buildTowerAt(1, [6, 6]),
    ] },
    { level: 6, solution: [
        buildTowerAt(2, [6, 2]),
        buildTowerAt(3, [6, 1]),
        buildTowerAt(2, [4, 10]),
        buildTowerAt(2, [4, 9]),
        waitForWaveIndex(0),
        buildTowerAt(2, [3, 9]),
        waitForWaveIndex(1),
        buildTowerAt(3, [6, 1]),
        buildTowerAt(3, [6, 1]),
        waitForWaveIndex(2),
        buildTowerAt(3, [3, 8]),
        buildTowerAt(3, [3, 8]),
        waitForWaveIndex(3),
        buildTowerAt(3, [3, 8]),
        buildTowerAt(3, [10, 9]),
        waitForWaveIndex(4),
        buildTowerAt(1, [10, 10]),
        buildTowerAt(3, [5, 1]),
        waitForWaveIndex(5),
        buildTowerAt(1, [5, 2]),
        waitForWaveIndex(6),
        buildTowerAt(2, [3, 9]),
        buildTowerAt(2, [3, 9]),
        buildTowerAt(3, [10, 9]),
        buildTowerAt(3, [5, 1]),
        waitForWaveIndex(7),
        buildTowerAt(3, [5, 1]),
        waitForWaveIndex(8),
        buildTowerAt(1, [10, 10]),
        buildTowerAt(1, [10, 10]),
    ] },
    // This level solution uses blue walls to redirect
    // the boss after it passes certain towers. The "solution"
    // probably fails.
    { level: 7, tag: 'complex', solution: [
        buildTowerAt(2, [6, 11]),
        buildTowerAt(2, [6, 12]),
        buildTowerAt(3, [4, 3]),
        waitForWaveIndex(0),
        buildTowerAt(2, [4, 8]),
        buildTowerAt(2, [4, 7]),
        waitForWaveIndex(1),
        buildTowerAt(3, [9, 6]),
        buildTowerAt(3, [13, 5]),
        waitForWaveIndex(2),
        buildTowerAt(2, [4, 7]),
        waitForWaveIndex(3),
        buildTowerAt(2, [4, 7]),
        waitForWaveIndex(4),
        buildTowerAt(2, [4, 8]),
        waitForWaveIndex(5),
        buildTowerAt(2, [4, 8]),
        waitForWaveIndex(6),
        buildTowerAt(2, [6, 11]),
        waitForWaveIndex(7),
        buildTowerAt(2, [6, 11]),
        buildTowerAt(2, [6, 12]),
        waitForWaveIndex(8),
        buildTowerAt(2, [6, 12]),
        waitForWaveIndex(9),
        buildTowerAt(3, [3, 8]),
        buildTowerAt(3, [7, 12]),
        buildTowerAt(3, [3, 8]),
        buildTowerAt(3, [3, 12]),
        buildTowerAt(3, [6, 9]),
    ] },
    { level: 8, solution: [
        waitForWaveIndex(0),
        buildTowerAt(2, [5, 8]),
        buildTowerAt(3, [4, 8]),
        buildTowerAt(2, [9, 11]),
        buildTowerAt(1, [10, 11]),
        waitForWaveIndex(1),
        buildTowerAt(1, [8, 7]),
        waitForWaveIndex(2),
        waitForWaveIndex(3),
        buildTowerAt(3, [4, 9]),
        buildTowerAt(3, [5, 9]),
        waitForWaveIndex(4),
        buildTowerAt(2, [11, 11]),
        buildTowerAt(3, [10, 10]),
        buildTowerAt(3, [10, 10]),
        buildTowerAt(3, [10, 10]),
        waitForWaveIndex(5),
        buildTowerAt(2, [11, 11]),
        buildTowerAt(2, [11, 11]),
        waitForWaveIndex(6),
        buildTowerAt(1, [10, 11]),
        buildTowerAt(1, [10, 11]),
        waitForWaveIndex(7),
        buildTowerAt(2, [9, 11]),
        buildTowerAt(2, [9, 11]),
        waitForWaveIndex(8),
        buildTowerAt(3, [5, 9]),
        buildTowerAt(3, [5, 9]),
        waitForWaveIndex(9),
        buildTowerAt(3, [4, 9]),
        buildTowerAt(3, [4, 9]),
        buildTowerAt(3, [4, 8]),
        buildTowerAt(3, [4, 8]),
        buildTowerAt(3, [11, 13]),
        buildTowerAt(1, [12, 13]),
        buildTowerAt(1, [12, 13]),
    ] },
    { level: 9, solution: [
        buildTowerAt(2, [6, 5]),
        buildTowerAt(3, [9, 2]),
        buildTowerAt(2, [9, 1]),
        buildTowerAt(3, [6, 4]),
        buildTowerAt(3, [9, 2]),
        waitForWaveIndex(0),
        buildTowerAt(3, [5, 12]),
        waitForWaveIndex(1),
        buildTowerAt(1, [6, 12]),
        buildTowerAt(3, [6, 4]),
        waitForWaveIndex(2),
        buildTowerAt(3, [9, 2]),
        waitForWaveIndex(3),
        buildTowerAt(3, [5, 12]),
        buildTowerAt(3, [5, 12]),
        waitForWaveIndex(4),
        buildTowerAt(1, [7, 5]),
        waitForWaveIndex(5),
        buildTowerAt(3, [7, 4]),
        buildTowerAt(2, [11, 8]),
        waitForWaveIndex(6),
        buildTowerAt(2, [6, 5]),
        buildTowerAt(1, [6, 12]),
        buildTowerAt(1, [6, 12]),
        buildTowerAt(3, [6, 4]),
        waitForWaveIndex(7),
        buildTowerAt(3, [7, 4]),
        buildTowerAt(3, [7, 4]),
        buildTowerAt(2, [6, 5]),
        waitForWaveIndex(8),
        buildTowerAt(1, [7, 5]),
        buildTowerAt(1, [7, 5]),
        waitForWaveIndex(9),
        buildTowerAt(2, [11, 10]),
        buildTowerAt(1, [11, 9]),
        buildTowerAt(3, [12, 9]),
        buildTowerAt(2, [11, 10]),
        buildTowerAt(2, [11, 10]),
        waitForWaveIndex(10),
        buildTowerAt(2, [11, 8]),
    ] },
    { level: 10, solution: [
        buildTowerAt(1, [8, 12]),
        buildTowerAt(3, [8, 11]),
        buildTowerAt(2, [4, 6]),
        buildTowerAt(2, [5, 6]),
        waitForWaveIndex(0),
        buildTowerAt(3, [6, 5]),
        buildTowerAt(3, [8, 10]),
        waitForWaveIndex(1),
        buildTowerAt(2, [5, 5]),
        waitForWaveIndex(2),
        buildTowerAt(2, [3, 10]),
        waitForWaveIndex(3),
        buildTowerAt(1, [3, 9]),
        waitForWaveIndex(4),
        buildTowerAt(1, [3, 11]),
        waitForWaveIndex(5),
        buildTowerAt(2, [3, 10]),
        buildTowerAt(2, [3, 10]),
        waitForWaveIndex(6),
        buildTowerAt(1, [3, 11]),
        buildTowerAt(1, [3, 9]),
        buildTowerAt(3, [1, 11]),
        waitForWaveIndex(7),
        buildTowerAt(3, [2, 11]),
        buildTowerAt(3, [2, 12]),
        buildTowerAt(3, [1, 12]),
        buildTowerAt(3, [1, 12]),
        waitForWaveIndex(8),
        buildTowerAt(1, [3, 11]),
        buildTowerAt(1, [3, 9]),
        waitForWaveIndex(9),
        buildTowerAt(3, [2, 12]),
        buildTowerAt(3, [2, 12]),
        buildTowerAt(3, [2, 11]),
        buildTowerAt(3, [2, 11]),
        waitForWaveIndex(10),
        buildTowerAt(2, [4, 11]),
        buildTowerAt(3, [1, 12]),
        buildTowerAt(3, [1, 11]),
        buildTowerAt(3, [1, 11]),
        buildTowerAt(2, [4, 11]),
        waitForWaveIndex(11),
    ] },
    { level: 11, solution: [
        buildTowerAt(2, [10, 1]),
        buildTowerAt(3, [11, 1]),
        buildTowerAt(3, [4, 2]),
        buildTowerAt(2, [5, 2]),
        buildTowerAt(3, [8, 2]),
        waitForWaveIndex(0),
        buildTowerAt(2, [9, 2]),
        waitForWaveIndex(1),
        buildTowerAt(2, [9, 3]),
        waitForWaveIndex(2),
        buildTowerAt(2, [5, 3]),
        waitForWaveIndex(3),
        buildTowerAt(2, [10, 2]),
        waitForWaveIndex(4),
        buildTowerAt(3, [6, 4]),
        buildTowerAt(2, [7, 4]),
        waitForWaveIndex(5),
        buildTowerAt(2, [7, 5]),
        waitForWaveIndex(6),
        buildTowerAt(2, [6, 7]),
        buildTowerAt(3, [6, 6]),
        buildTowerAt(2, [5, 7]),
        buildTowerAt(3, [8, 12]),
        waitForWaveIndex(7),
        buildTowerAt(1, [8, 11]),
        buildTowerAt(1, [8, 11]),
        buildTowerAt(1, [8, 11]),
        waitForWaveIndex(8),
        buildTowerAt(3, [6, 6]),
        buildTowerAt(3, [6, 6]),
        waitForWaveIndex(9),
        buildTowerAt(3, [8, 12]),
        buildTowerAt(3, [8, 12]),
        waitForWaveIndex(10),
        buildTowerAt(2, [7, 4]),
        buildTowerAt(2, [7, 4]),
        buildTowerAt(2, [7, 5]),
        waitForWaveIndex(11),
    ] },
    { level: 12, solution: [
        buildTowerAt(3, [3, 6]),
        buildTowerAt(3, [2, 7]),
        buildTowerAt(2, [4, 6]),
        buildTowerAt(2, [2, 8]),
        waitForWaveIndex(0),
        buildTowerAt(2, [3, 9]),
        buildTowerAt(3, [3, 10]),
        waitForWaveIndex(1),
        waitForWaveIndex(2),
        waitForWaveIndex(3),
        buildTowerAt(3, [3, 6]),
        buildTowerAt(3, [2, 7]),
        buildTowerAt(3, [3, 10]),
        buildTowerAt(3, [3, 6]),
        buildTowerAt(3, [2, 7]),
        waitForWaveIndex(4),
        buildTowerAt(3, [3, 10]),
        buildTowerAt(2, [11, 9]),
        buildTowerAt(2, [11, 9]),
        waitForWaveIndex(5),
        buildTowerAt(2, [11, 9]),
        waitForWaveIndex(6),
        waitForWaveIndex(7),
        buildTowerAt(2, [4, 7]),
        buildTowerAt(2, [4, 9]),
        buildTowerAt(2, [3, 8]),
        buildTowerAt(2, [4, 7]),
        buildTowerAt(2, [3, 8]),
        waitForWaveIndex(8),
        waitForWaveIndex(9),
        buildTowerAt(3, [12, 10]),
        buildTowerAt(3, [12, 11]),
        buildTowerAt(3, [11, 11]),
        buildTowerAt(3, [11, 10]),
        buildTowerAt(3, [11, 10]),
        buildTowerAt(3, [12, 10]),
        waitForWaveIndex(10),
        buildTowerAt(2, [13, 11]),
        buildTowerAt(2, [13, 11]),
        waitForWaveIndex(11),
        buildTowerAt(2, [13, 11]),
        buildTowerAt(2, [4, 7]),
        buildTowerAt(2, [13, 12]),
        buildTowerAt(3, [12, 12]),
        buildTowerAt(3, [12, 12]),
        buildTowerAt(3, [12, 12]),
    ] },
    { level: 13, solution: [
        buildTowerAt(1, [5, 1]),
        buildTowerAt(2, [6, 1]),
        buildTowerAt(2, [5, 3]),
        waitForWaveIndex(0),
        buildTowerAt(1, [5, 2]),
        waitForWaveIndex(1),
        buildTowerAt(2, [2, 10]),
        waitForWaveIndex(2),
        waitForWaveIndex(3),
        buildTowerAt(1, [5, 4]),
        buildTowerAt(2, [5, 3]),
        waitForWaveIndex(4),
        buildTowerAt(2, [5, 3]),
        waitForWaveIndex(5),
        waitForWaveIndex(6),
        buildTowerAt(2, [6, 1]),
        buildTowerAt(2, [6, 1]),
        buildTowerAt(1, [5, 4]),
        buildTowerAt(1, [5, 4]),
        waitForWaveIndex(7),
        buildTowerAt(1, [5, 2]),
        waitForWaveIndex(8),
        buildTowerAt(1, [5, 2]),
        waitForWaveIndex(9),
        buildTowerAt(2, [5, 5]),
        buildTowerAt(2, [5, 5]),
        buildTowerAt(2, [5, 5]),
        buildTowerAt(1, [5, 6]),
        buildTowerAt(1, [5, 6]),
        waitForWaveIndex(10),
        buildTowerAt(1, [5, 6]),
        buildTowerAt(1, [5, 1]),
        buildTowerAt(1, [5, 1]),
        waitForWaveIndex(11),
        waitForWaveIndex(12),
        buildTowerAt(2, [4, 11]),
        buildTowerAt(2, [4, 13]),
        buildTowerAt(2, [2, 13]),
        buildTowerAt(2, [2, 11]),
    ] },
    { level: 14, solution: [
        buildTowerAt(3, [6, 9]),
        buildTowerAt(3, [8, 9]),
        buildTowerAt(1, [8, 8]),
        buildTowerAt(3, [8, 9]),
        buildTowerAt(3, [6, 9]),
        waitForWaveIndex(0),
        buildTowerAt(3, [8, 9]),
        waitForWaveIndex(1),
        buildTowerAt(3, [6, 9]),
        waitForWaveIndex(2),
        waitForWaveIndex(3),
        buildTowerAt(1, [9, 8]),
        buildTowerAt(1, [9, 8]),
        waitForWaveIndex(4),
        buildTowerAt(3, [9, 6]),
        buildTowerAt(3, [9, 7]),
        waitForWaveIndex(5),
        buildTowerAt(3, [10, 7]),
        buildTowerAt(3, [10, 6]),
        waitForWaveIndex(6),
        buildTowerAt(3, [10, 6]),
        waitForWaveIndex(7),
        buildTowerAt(3, [10, 6]),
        waitForWaveIndex(8),
        buildTowerAt(1, [9, 8]),
        buildTowerAt(1, [8, 8]),
        buildTowerAt(1, [8, 8]),
        waitForWaveIndex(9),
        buildTowerAt(3, [10, 7]),
        buildTowerAt(3, [10, 7]),
        buildTowerAt(3, [9, 7]),
        buildTowerAt(3, [9, 7]),
        buildTowerAt(3, [9, 6]),
        waitForWaveIndex(10),
        waitForWaveIndex(11),
        buildTowerAt(3, [9, 6]),
        buildTowerAt(1, [6, 10]),
        buildTowerAt(1, [6, 10]),
        waitForWaveIndex(12),
    ] },
    { level: 15, solution: [
        buildTowerAt(2, [4, 6]),
        buildTowerAt(2, [6, 6]),
        buildTowerAt(1, [5, 6]),
        waitForWaveIndex(0),
        buildTowerAt(3, [9, 6]),
        waitForWaveIndex(1),
        buildTowerAt(1, [9, 7]),
        waitForWaveIndex(2),
        buildTowerAt(1, [10, 7]),
        buildTowerAt(3, [5, 7]),
        waitForWaveIndex(3),
        waitForWaveIndex(4),
        buildTowerAt(1, [8, 7]),
        buildTowerAt(2, [9, 8]),
        buildTowerAt(3, [5, 7]),
        waitForWaveIndex(5),
        buildTowerAt(3, [5, 7]),
        buildTowerAt(3, [9, 6]),
        buildTowerAt(3, [9, 6]),
        waitForWaveIndex(6),
        buildTowerAt(2, [6, 6]),
        buildTowerAt(2, [6, 6]),
        waitForWaveIndex(7),
        buildTowerAt(2, [4, 6]),
        buildTowerAt(2, [4, 6]),
        waitForWaveIndex(8),
        buildTowerAt(1, [9, 7]),
        buildTowerAt(1, [9, 7]),
        buildTowerAt(1, [10, 7]),
        waitForWaveIndex(9),
        buildTowerAt(2, [9, 8]),
        buildTowerAt(2, [9, 8]),
        buildTowerAt(1, [8, 7]),
        waitForWaveIndex(10),
        buildTowerAt(1, [5, 6]),
        buildTowerAt(1, [5, 6]),
        buildTowerAt(1, [8, 7]),
        waitForWaveIndex(11),
        buildTowerAt(1, [10, 7]),
        buildTowerAt(2, [6, 11]),
        buildTowerAt(3, [6, 12]),
        buildTowerAt(3, [6, 12]),
        buildTowerAt(3, [6, 12]),
        buildTowerAt(2, [6, 11]),
        waitForWaveIndex(12),
        buildTowerAt(2, [6, 11]),
        buildTowerAt(3, [5, 12]),
        buildTowerAt(3, [5, 11]),
        waitForWaveIndex(13),
        buildTowerAt(3, [5, 11]),
        buildTowerAt(3, [5, 11]),
        buildTowerAt(3, [5, 12]),
        buildTowerAt(3, [5, 12]),
        buildTowerAt(3, [11, 10]),
        buildTowerAt(2, [10, 10]),
        buildTowerAt(3, [11, 11]),
        waitForWaveIndex(14),
        buildTowerAt(3, [10, 11]),
        buildTowerAt(2, [10, 10]),
        buildTowerAt(2, [10, 10]),
        waitForWaveIndex(15),
        buildTowerAt(3, [11, 10]),
        buildTowerAt(3, [11, 10]),
        buildTowerAt(3, [10, 11]),
    ] },
    { level: 16, solution: [
        buildTowerAt(2, [3, 10]),
        buildTowerAt(2, [5, 10]),
        buildTowerAt(3, [4, 11]),
        waitForWaveIndex(0),
        waitForWaveIndex(1),
        buildTowerAt(1, [4, 10]),
        buildTowerAt(3, [4, 11]),
        buildTowerAt(3, [4, 11]),
        buildTowerAt(2, [5, 10]),
        waitForWaveIndex(2),
        waitForWaveIndex(3),
        buildTowerAt(1, [10, 8]),
        waitForWaveIndex(4),
        buildTowerAt(1, [10, 9]),
        waitForWaveIndex(5),
        buildTowerAt(1, [10, 10]),
        waitForWaveIndex(6),
        buildTowerAt(2, [9, 9]),
        buildTowerAt(3, [11, 9]),
        buildTowerAt(2, [5, 10]),
        buildTowerAt(2, [3, 10]),
        buildTowerAt(3, [11, 9]),
        buildTowerAt(3, [11, 9]),
        waitForWaveIndex(7),
        buildTowerAt(2, [9, 9]),
        buildTowerAt(2, [9, 9]),
        buildTowerAt(1, [4, 10]),
        waitForWaveIndex(8),
        buildTowerAt(1, [10, 9]),
        waitForWaveIndex(9),
        buildTowerAt(1, [10, 9]),
        buildTowerAt(1, [10, 8]),
        buildTowerAt(1, [10, 8]),
        waitForWaveIndex(10),
        buildTowerAt(1, [10, 10]),
        waitForWaveIndex(11),
        buildTowerAt(1, [10, 10]),
        buildTowerAt(1, [4, 10]),
        buildTowerAt(2, [3, 10]),
        buildTowerAt(2, [7, 12]),
        waitForWaveIndex(12),
        buildTowerAt(2, [5, 12]),
        buildTowerAt(3, [6, 11]),
        buildTowerAt(1, [6, 12]),
        buildTowerAt(3, [6, 11]),
        buildTowerAt(3, [6, 11]),
        buildTowerAt(3, [9, 5]),
        buildTowerAt(3, [9, 4]),
        buildTowerAt(3, [8, 4]),
        waitForWaveIndex(13),
        buildTowerAt(3, [8, 5]),
        buildTowerAt(3, [8, 5]),
        buildTowerAt(3, [8, 5]),
        waitForWaveIndex(14),
        buildTowerAt(3, [9, 5]),
        buildTowerAt(3, [9, 5]),
        buildTowerAt(3, [9, 4]),
        buildTowerAt(3, [9, 4]),
        buildTowerAt(3, [8, 4]),
        buildTowerAt(3, [8, 4]),
        waitForWaveIndex(15),
        buildTowerAt(2, [7, 12]),
        buildTowerAt(2, [7, 12]),
        buildTowerAt(2, [5, 12]),
        buildTowerAt(2, [5, 12]),
        waitForWaveIndex(16),
        buildTowerAt(1, [6, 12]),
        buildTowerAt(1, [6, 12]),
        waitForWaveIndex(17),
    ] },

    { level: 17, solution: [
        buildTowerAt(2, [7, 5]),
        buildTowerAt(2, [9, 5]),
        buildTowerAt(1, [8, 5]),
        buildTowerAt(3, [8, 6]),
        waitForWaveIndex(0),
        buildTowerAt(3, [8, 6]),
        buildTowerAt(3, [8, 6]),
        waitForWaveIndex(1),
        buildTowerAt(2, [3, 13]),
        waitForWaveIndex(2),
        waitForWaveIndex(3),
        buildTowerAt(1, [7, 11]),
        buildTowerAt(1, [7, 12]),
        waitForWaveIndex(4),
        buildTowerAt(2, [8, 12]),
        waitForWaveIndex(5),
        buildTowerAt(1, [7, 13]),
        buildTowerAt(3, [6, 12]),
        waitForWaveIndex(6),
        buildTowerAt(3, [7, 10]),
        buildTowerAt(3, [9, 12]),
        buildTowerAt(3, [6, 12]),
        waitForWaveIndex(7),
        buildTowerAt(1, [8, 5]),
        buildTowerAt(2, [9, 5]),
        waitForWaveIndex(8),
        buildTowerAt(2, [9, 5]),
        buildTowerAt(2, [3, 13]),
        buildTowerAt(2, [3, 13]),
        buildTowerAt(2, [7, 5]),
        waitForWaveIndex(9),
        waitForWaveIndex(10),
        buildTowerAt(2, [7, 5]),
        buildTowerAt(1, [8, 5]),
        buildTowerAt(2, [2, 13]),
        buildTowerAt(2, [2, 13]),
        buildTowerAt(2, [2, 13]),
        waitForWaveIndex(11),
        buildTowerAt(3, [6, 12]),
        buildTowerAt(2, [8, 12]),
        buildTowerAt(2, [8, 12]),
        waitForWaveIndex(12),
        buildTowerAt(1, [7, 12]),
        buildTowerAt(1, [7, 12]),
        buildTowerAt(1, [7, 11]),
        buildTowerAt(1, [7, 11]),
        buildTowerAt(1, [7, 13]),
        buildTowerAt(1, [7, 13]),
        waitForWaveIndex(13),
        buildTowerAt(2, [3, 15]),
        buildTowerAt(1, [3, 14]),
        buildTowerAt(3, [2, 14]),
        waitForWaveIndex(14),
        buildTowerAt(3, [2, 14]),
        buildTowerAt(3, [2, 14]),
        waitForWaveIndex(15),
        buildTowerAt(1, [3, 14]),
        buildTowerAt(1, [3, 14]),
        buildTowerAt(2, [3, 15]),
        buildTowerAt(2, [3, 15]),
        buildTowerAt(3, [12, 11]),
        buildTowerAt(3, [12, 12]),
        buildTowerAt(3, [13, 12]),
        buildTowerAt(3, [13, 11]),
        waitForWaveIndex(16),
        buildTowerAt(3, [13, 11]),
        buildTowerAt(3, [13, 11]),
        buildTowerAt(3, [12, 11]),
        buildTowerAt(3, [12, 12]),
        buildTowerAt(3, [12, 12]),
        buildTowerAt(3, [13, 12]),
        buildTowerAt(3, [12, 11]),
        waitForWaveIndex(17),
        buildTowerAt(3, [13, 12]),
        waitForWaveIndex(18),
        waitForWaveIndex(19),
        buildTowerAt(2, [13, 10]),
        buildTowerAt(2, [13, 10]),
        buildTowerAt(2, [13, 10]),
        buildTowerAt(2, [14, 11]),
        buildTowerAt(2, [14, 11]),
        buildTowerAt(2, [14, 11]),
        buildTowerAt(2, [12, 7]),
        buildTowerAt(2, [12, 7]),
        buildTowerAt(2, [12, 7]),
        buildTowerAt(2, [11, 7]),
        buildTowerAt(2, [11, 7]),
        buildTowerAt(2, [11, 7]),
        buildTowerAt(2, [10, 7]),
        buildTowerAt(2, [10, 7]),
        buildTowerAt(2, [10, 7]),
    ] },

    { level: 18, solution: [
        buildTowerAt(2, [5, 2]),
        buildTowerAt(2, [4, 1]),
        buildTowerAt(3, [6, 2]),
        buildTowerAt(3, [3, 1]),
        waitForWaveIndex(0),
        buildTowerAt(2, [8, 12]),
        buildTowerAt(3, [13, 8]),
        waitForWaveIndex(1),
        buildTowerAt(3, [9, 6]),
        buildTowerAt(1, [10, 6]),
        waitForWaveIndex(2),
        buildTowerAt(3, [9, 7]),
        waitForWaveIndex(3),
        buildTowerAt(2, [10, 7]),
        waitForWaveIndex(4),
        buildTowerAt(3, [9, 6]),
        buildTowerAt(3, [9, 6]),
        buildTowerAt(3, [9, 7]),
        waitForWaveIndex(5),
        buildTowerAt(3, [9, 7]),
        buildTowerAt(2, [8, 12]),
        buildTowerAt(2, [8, 12]),
        buildTowerAt(1, [10, 6]),
        waitForWaveIndex(6),
        buildTowerAt(1, [10, 6]),
        buildTowerAt(2, [10, 7]),
        buildTowerAt(2, [10, 7]),
        waitForWaveIndex(7),
        buildTowerAt(1, [2, 7]),
        buildTowerAt(1, [4, 7]),
        waitForWaveIndex(8),
        buildTowerAt(2, [3, 7]),
        buildTowerAt(2, [3, 7]),
        buildTowerAt(2, [3, 7]),
        waitForWaveIndex(9),
        buildTowerAt(1, [12, 7]),
        buildTowerAt(1, [13, 7]),
        waitForWaveIndex(10),
        buildTowerAt(1, [14, 7]),
        buildTowerAt(2, [13, 6]),
        waitForWaveIndex(11),
        buildTowerAt(3, [7, 7]),
        buildTowerAt(3, [7, 6]),
        buildTowerAt(3, [8, 6]),
        buildTowerAt(3, [8, 7]),
        buildTowerAt(3, [7, 7]),
        buildTowerAt(3, [7, 6]),
        buildTowerAt(3, [8, 6]),
        waitForWaveIndex(12),
        buildTowerAt(3, [8, 7]),
        buildTowerAt(3, [7, 7]),
        buildTowerAt(3, [7, 6]),
        buildTowerAt(3, [8, 6]),
        waitForWaveIndex(13),
        buildTowerAt(1, [13, 7]),
        buildTowerAt(1, [13, 7]),
        buildTowerAt(1, [12, 7]),
        buildTowerAt(1, [12, 7]),
        waitForWaveIndex(14),
        buildTowerAt(1, [14, 7]),
        buildTowerAt(1, [14, 7]),
        buildTowerAt(2, [13, 6]),
        waitForWaveIndex(15),
        buildTowerAt(2, [13, 6]),
        buildTowerAt(3, [13, 8]),
        buildTowerAt(3, [13, 8]),
        waitForWaveIndex(16),
        buildTowerAt(3, [8, 11]),
        buildTowerAt(3, [8, 11]),
        buildTowerAt(3, [8, 11]),
        buildTowerAt(3, [9, 11]),
        buildTowerAt(3, [9, 11]),
        buildTowerAt(3, [9, 11]),
        waitForWaveIndex(17),
        buildTowerAt(3, [8, 7]),
        waitForWaveIndex(18),
        buildTowerAt(3, [9, 12]),
        buildTowerAt(3, [9, 12]),
        buildTowerAt(3, [9, 12]),
        buildTowerAt(3, [3, 10]),
        buildTowerAt(3, [3, 9]),
        buildTowerAt(3, [2, 9]),
        buildTowerAt(2, [2, 10]),
        buildTowerAt(3, [4, 12]),
        buildTowerAt(3, [4, 11]),
        buildTowerAt(3, [3, 11]),
        buildTowerAt(2, [3, 12]),
        buildTowerAt(2, [2, 10]),
        buildTowerAt(2, [2, 10]),
        buildTowerAt(2, [3, 12]),
        buildTowerAt(2, [3, 12]),
        waitForWaveIndex(19),
        buildTowerAt(2, [12, 4]),
        buildTowerAt(2, [12, 4]),
        buildTowerAt(2, [12, 4]),
        buildTowerAt(3, [12, 5]),
        buildTowerAt(3, [13, 5]),
        buildTowerAt(3, [13, 4]),
        waitForWaveIndex(20),
        buildTowerAt(3, [13, 4]),
        buildTowerAt(3, [13, 4]),
        buildTowerAt(3, [13, 5]),
        buildTowerAt(3, [12, 5]),
        buildTowerAt(3, [12, 5]),
        buildTowerAt(3, [13, 5]),
        buildTowerAt(3, [3, 9]),
        buildTowerAt(3, [3, 9]),
        buildTowerAt(3, [2, 9]),
        buildTowerAt(3, [2, 9]),
        buildTowerAt(3, [3, 10]),
        buildTowerAt(3, [3, 10]),
        buildTowerAt(3, [4, 11]),
        buildTowerAt(3, [4, 11]),
        buildTowerAt(3, [4, 12]),
        buildTowerAt(3, [4, 12]),
        buildTowerAt(3, [3, 11]),
        buildTowerAt(3, [3, 11]),
        buildTowerAt(1, [8, 14]),
        buildTowerAt(1, [8, 14]),
        buildTowerAt(1, [8, 14]),
        buildTowerAt(3, [9, 14]),
        buildTowerAt(3, [11, 14]),
        buildTowerAt(1, [11, 13]),
        buildTowerAt(1, [11, 13]),
        buildTowerAt(1, [11, 13]),
        buildTowerAt(3, [11, 14]),
        buildTowerAt(3, [11, 14]),
        buildTowerAt(3, [9, 14]),
        buildTowerAt(3, [9, 14]),
    ] },
];

window.onload = async () => {
    const ATTEMPTS = 50;
    // mocks
    GameState.startNextWaveButton = document.createElement('div');
    GameState.runebook = document.createElement('div');
    GameState.waveInfoToast = document.createElement('div');
    window.debugTowerBuildLog = [];
    ParticleSystem.addParticle = () => {};
    ParticleSystem.spawnParticlePixelLine = () => {};
    ParticleSystem.sparkleRect = () => {};
    ParticleSystem.explodeSpritesAt = () => {};
    ParticleSystem.sparkleSpriteAt = () => {};
    ParticleSystem.explodeManaAt = () => {};
    ParticleSystem.spawnFireCircleAt = () => {};
    AudioSystem.scheduleNote = () => {};

    const status = div('');
    document.body.append(status);

    for(const {level, tag='', solution} of solutions.reverse()) {
        let totalHealth = 0;
        let totalMana = 0;
        let perfects = 0;
        let passes = 0;
        let towers = new Set();
        for(const attempt of range(ATTEMPTS)) {
            status.innerText = `Running: Level ${level}, attempt ${attempt}/${ATTEMPTS}.`;
            await new Promise(res => setTimeout(res, 10));
            const [health, mana] = solveLevel(level, solution);
            totalHealth += health;
            totalMana += mana;
            perfects += health == 15 ? 1 : 0;
            passes += health > -1 ? 1 : 0;
            GameState.terrain.computedTowersArr.forEach((t, i) => {
                towers.add(`${i}=${t.displayName}(${t.level})`);
            });
        }
        document.body.append(div('solutionRow',
            div('cat', 'Level'), div('num', level, ' ', tag),
            div('cat', 'Health'), div('num', (totalHealth / ATTEMPTS).toFixed(1)),
            div('cat', 'Mana'), div('num', (totalMana / ATTEMPTS).toFixed(1)),
            div('cat', 'Pass'), div('num', (passes / ATTEMPTS * 100).toFixed(0), '%'),
            div('cat', 'Perfect'), div('num', (perfects / ATTEMPTS * 100).toFixed(0), '%'),
            div('', [...towers].toSorted().join(', '))
        ));
    }
    status.innerText = `Done.`;
}
